import { Appointment } from "@/types/Appointment";

export const appointmentsMockup: Appointment[] = [
  // --- Agendamentos Passados ---
  {
    id: "1",
    providerName: "Ana Limpeza & Cia",
    clientName: "Maria Santos",
    service: "Limpeza Pós-Obra",
    date: "2025-08-28",
    time: "09:00",
    endTime: "13:00",
    status: "completed",
    price: "R$ 350,00",
    phone: "(11) 91234-5678",
    email: "maria.santos@email.com",
    notes: "Foco na remoção de poeira de gesso.",
    location: "Rua das Flores, 123",
    duration: "4h",
    paymentMethod: "pix",
    whatsapp: "(11) 91234-5678",
    canReview: false, // Cliente já avaliou
    rating: 5,
  },
  {
    id: "2",
    providerName: "João Eletricista",
    clientName: "Carlos Mendes",
    service: "Instalação de Luminárias",
    date: "2025-09-01",
    time: "14:00",
    endTime: "16:00",
    status: "completed",
    price: "R$ 180,00",
    phone: "(21) 98877-6655",
    email: "carlos.mendes@email.com",
    location: "Av. Principal, 456",
    duration: "2h",
    paymentMethod: "credito",
    whatsapp: "(21) 98877-6655",
    canReview: true, // Cliente ainda pode avaliar
  },

  // --- Agendamentos de Hoje (03/09/2025) ---
  {
    id: "3",
    providerName: "Beatriz Manicure",
    clientName: "Juliana Costa",
    service: "Manicure e Pedicure",
    date: "2025-09-03",
    time: "10:00",
    endTime: "11:30",
    status: "upcoming",
    price: "R$ 75,00",
    phone: "(31) 99911-2233",
    email: "juliana.costa@email.com",
    notes: "Cliente pediu esmalte hipoalergênico.",
    location: "Salão Beleza Pura",
    duration: "1h30",
    paymentMethod: "debito",
    whatsapp: "(31) 99911-2233",
    canReview: false,
  },
  {
    id: "4",
    providerName: "Hidráulica Veloz",
    clientName: "Pedro Oliveira",
    service: "Reparo de Vazamento",
    date: "2025-09-03",
    time: "15:00",
    endTime: "16:00",
    status: "upcoming",
    price: "R$ 220,00",
    phone: "(41) 98888-4444",
    email: "pedro.oliveira@email.com",
    location: "Condomínio Vila Real, Bloco C, Ap 101",
    duration: "1h",
    paymentMethod: "pix",
    whatsapp: "(41) 98888-4444",
    canReview: false,
    rescheduleStatus: "pending", // Solicitação de reagendamento
    newDate: "2025-09-05",
    newTime: "10:00",
  },

  // --- Próximos Agendamentos ---
  {
    id: "5",
    providerName: "Mundo Verde Jardinagem",
    clientName: "Fernanda Lima",
    service: "Manutenção de Jardim",
    date: "2025-09-05",
    time: "08:00",
    endTime: "12:00",
    status: "upcoming",
    price: "R$ 250,00",
    phone: "(51) 99955-8899",
    email: "fernanda.lima@email.com",
    location: "Rua das Gaivotas, 789",
    duration: "4h",
    paymentMethod: "credito",
    whatsapp: "(51) 99955-8899",
    canReview: false,
  },
  {
    id: "6",
    providerName: "PetWalker Feliz",
    clientName: "Roberto Alves",
    service: "Passeio com Cães",
    date: "2025-09-08",
    time: "17:00",
    endTime: "18:00",
    status: "upcoming",
    price: "R$ 50,00",
    phone: "(61) 98123-4567",
    email: "roberto.alves@email.com",
    notes: "Dois cachorros, um Poodle e um Labrador.",
    location: "Parque da Cidade",
    duration: "1h",
    paymentMethod: "pix",
    whatsapp: "(61) 98123-4567",
    canReview: false,
  },
  {
    id: "7",
    providerName: "Pinta Tudo",
    clientName: "Luciana Pereira",
    service: "Pintura Interna (Quarto)",
    date: "2025-09-10",
    time: "09:00",
    endTime: "17:00",
    status: "upcoming",
    price: "R$ 400,00",
    phone: "(71) 99234-5678",
    email: "luciana.p@email.com",
    location: "Alameda dos Bosques, 321",
    duration: "8h",
    paymentMethod: "credito",
    whatsapp: "(71) 99234-5678",
    canReview: false,
  },
  {
    id: "8",
    providerName: "Foco na Ordem",
    clientName: "Camila Rodrigues",
    service: "Organização de Escritório",
    date: "2025-09-12",
    time: "13:00",
    endTime: "17:00",
    status: "upcoming",
    price: "R$ 300,00",
    phone: "(81) 99876-5432",
    email: "camila.r@email.com",
    location: "Empresa InovaTech, Sala 3",
    duration: "4h",
    paymentMethod: "debito",
    whatsapp: "(81) 99876-5432",
    canReview: false,
  },
];